### PR TITLE
Adding review

### PR DESCRIPTION
**Pull request by beulah-s**
Hi Elizabeth, Please find my review as an Rmd file. Excellent work with the coding!

### CODE REVIEW

**Comment by ekmcmurchie** [comment]
Thanks for the review!

I have just one question: by "see how many of those individual SNPs are
present in the maize group and teosinte group", do you mean the total
number of SNP positions for maize vs. the total number of SNP positions for
maize?

Sincerely,

Elizabeth

**Comment by beulah-s** [comment]
Hi Elizabeth,

Yes, when we transpose the maize or teosinte file, I observed that although
they both had the same SNPs, the number of columns differ because there are
more maize groups with SNPs than the teosinte groups put together.

To plot them it took a few more steps -  1. Pivot the maize and teosinte
file individually and make them into a long file. 2. Add a column and name
them as "maize" or "teosinte". 3. Combine rows of the maize and teosinte
files and plot a graph for SNPs per chromosome across groups.

These are the codes I used:
data1 %>% pivot_longer(!c(Chromosome, SNP_ID, Position), names_to= "S.No",
values_to="Bases") %>% {.}
mutate(data1, Group = "Maize")
data2 %>% pivot_longer(!c(Chromosome, SNP_ID, Position), names_to= "S.No",
values_to="Bases") %>% {.}
mutate(data1, Group = "Teosinte")
boundfile <- bind_rows(data1, data2)
ggplot(boundfile, aes(x=Chromosome, fill= Group, Color=Group)) +
geom_bar(bins=10, position= "dodge")

I am not sure if it is worth looking at. Just thought that it would be
interesting :)

Once again, great job with your assignment!

Best,
Beulah

**Comment by ekmcmurchie** [comment]
Hi Beulah,

Are you sure that's right? We were only using three maize groups and three
teosinte groups.

Sincerely,

Elizabeth

**Comment by beulah-s** [comment]
Hi Elizabeth,

You are correct! We should be using only the three groups mentioned. I must
have gotten confused with the dataset. Sorry for the confusion! I will
change it in my review.

Thank you,
Beulah

**Pull request merged**
